version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=cf-deployment-1-laravelrdsinstance-2wofnhui8gtq.c1m64uowqls6.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=laravelDB
      - DB_USERNAME=admin
      - DB_PASSWORD=adminadmin
    volumes:
      - .:/var/www
